export const STAFF_PERMISSIONS = {
  USERS: 'users',
  INCOMING_REGISTRATIONS: 'incoming_registrations',
  TEAM_TASKS: 'team_tasks',
  DRIVERS: 'drivers',
  LIVE_MAP: 'live_map',
  KIT_ORDERS: 'kit_orders',
  BANNERS: 'banners',
  ADS: 'ads',
  BOOKINGS_ALL: 'bookings_all',
  BOOKINGS_SCHEDULED: 'bookings_scheduled',
  BOOKINGS_EMERGENCY: 'bookings_emergency',
  BOOKINGS_OUTSTATION: 'bookings_outstation',
  BOOKINGS_SUBSCRIPTION: 'bookings_subscription',
  ACCOUNT_REVENUE: 'account_revenue',
  ACCOUNT_SUB_REVENUE: 'account_sub_revenue',
  ACCOUNT_REFUNDS: 'account_refunds',
  FARE_MANAGEMENT: 'fare_management',
  SETTINGS_PLATFORM: 'settings_platform',
  SETTINGS_KITS: 'settings_kits',
  SETTINGS_ZONES: 'settings_zones',
  SETTINGS_TEAM: 'settings_team',
  DRIVER_WALLET: 'driver_wallet',
  REFERRALS: 'referrals',
};

export const PERMISSION_LABELS = {
  [STAFF_PERMISSIONS.USERS]: 'Manage Users',
  [STAFF_PERMISSIONS.INCOMING_REGISTRATIONS]: 'Incoming Registrations',
  [STAFF_PERMISSIONS.TEAM_TASKS]: 'Team Tasks',
  [STAFF_PERMISSIONS.DRIVERS]: 'Manage Drivers',
  [STAFF_PERMISSIONS.LIVE_MAP]: 'Live Map',
  [STAFF_PERMISSIONS.KIT_ORDERS]: 'Kit Orders',
  [STAFF_PERMISSIONS.BANNERS]: 'Top Banners',
  [STAFF_PERMISSIONS.ADS]: 'Ads',
  [STAFF_PERMISSIONS.BOOKINGS_ALL]: 'All Bookings',
  [STAFF_PERMISSIONS.BOOKINGS_SCHEDULED]: 'Scheduled Jobs',
  [STAFF_PERMISSIONS.BOOKINGS_EMERGENCY]: 'Schedule Pool',
  [STAFF_PERMISSIONS.BOOKINGS_OUTSTATION]: 'Outstation Pool',
  [STAFF_PERMISSIONS.BOOKINGS_SUBSCRIPTION]: 'Subscription Requests',
  [STAFF_PERMISSIONS.ACCOUNT_REVENUE]: 'Revenue',
  [STAFF_PERMISSIONS.ACCOUNT_SUB_REVENUE]: 'Subscription Revenue',
  [STAFF_PERMISSIONS.ACCOUNT_REFUNDS]: 'Refunds',
  [STAFF_PERMISSIONS.FARE_MANAGEMENT]: 'Fare Management',
  [STAFF_PERMISSIONS.SETTINGS_PLATFORM]: 'Platform Settings',
  [STAFF_PERMISSIONS.SETTINGS_KITS]: 'Driver Kits',
  [STAFF_PERMISSIONS.SETTINGS_ZONES]: 'Service Zones',
  [STAFF_PERMISSIONS.SETTINGS_TEAM]: 'Team Management',
  [STAFF_PERMISSIONS.DRIVER_WALLET]: 'Driver Wallet',
  [STAFF_PERMISSIONS.REFERRALS]: 'Refer & Earn',
};
